language: python
python:
  - "3.6"
script:
  - python -m pytest --cov=aws --cov=battlenet --cov=discord --cov=guild --cov=overwatch --cov=utils --cov=wow --cov-report xml:coverage.xml
after_success:
  - python-codacy-coverage -r coverage.xml
  - npm install
  - npm install serverless -g
  - serverless create_domain
  - serverless deploy --conceal