language: python
python:
  - "3.6"
script:
  - pytest --cov-report xml:coverage.xml
after_success:
  - python-codacy-coverage -r coverage.xml
  - npm install
  - npm install serverless -g
  - serverless create_domain
  - serverless deploy --conceal